name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# Limit permissions for GITHUB_TOKEN
permissions:
  contents: read
  checks: write    # Needed to write check results
  actions: read    # Needed to read action status
  pull-requests: write # Needed to comment on PRs with results
  packages: read   # Needed to read GitHub packages

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
    - name: Set up Go
      uses: actions/setup-go@v6
      with:
        go-version: '1.25'
        check-latest: true

    - name: Check out code
      uses: actions/checkout@v5

    - name: Verify Go module setup
      run: |
        go version
        go env GOPROXY
        go env GOMODCACHE
      shell: bash

    - name: List module files (Unix)
      if: runner.os != 'Windows'
      run: ls -la go.mod go.sum

    - name: List module files (Windows)
      if: runner.os == 'Windows'
      run: dir go.mod go.sum

    - name: Install dependencies
      run: |
        go mod download
        go mod verify
      shell: bash

    - name: Install golangci-lint
      uses: golangci/golangci-lint-action@v8
      with:
        version: v2.4.0
        install-mode: binary
    
    - name: Run tests with race detection
      run: |
        go list ./...
        go test -race -v ./...
      shell: bash

    - name: Run CI checks
      run: make ci
      shell: bash

    - name: Upload build artifacts
      uses: actions/upload-artifact@v5
      with:
        name: fabricator-${{ matrix.os }}
        path: build/fabricator
        retention-days: 7